services:
  - type: web
    name: mingpan-assistant
    env: python
    region: Oregon (US West)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true