services:
  - type: web
    name: ziwel-mingpan-assistant
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true